index:
    path: /
    controller: App\Controller\MainController::index

list:
    path: /liste
    controller: App\Controller\DiagnoseController::list

upload:
    path: /upload
    controller: App\Controller\DiagnoseController::upload